version: "3.8"

services:

  employee_db:
    container_name: employee_db
    build: ./employee_db
    environment:
      MYSQL_DATABASE: employee_data
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3306:3306
    volumes:
      - employee_data:/var/lib/mysql
    restart: on-failure

  login_db:
    container_name: login_db
    build: ./login_db
    environment:
      MYSQL_DATABASE: employee_login
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3307:3307
    volumes:
      - employee_login:/var/lib/mysql
    restart: on-failure
  
  eureka-discovery:
    container_name: employee-discovery-service
    build: ./eureka-discovery
    ports:
      - 8761:8761
    restart: on-failure
    
  spring-employee-service:
    container_name: spring-employee-service
    build: ./spring-employee-service
    ports:
      - 8082:8080
    depends_on:
      - employee_db
    restart: on-failure

  login-service:
    container_name: login-service
    build: ./login-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8083:8080
    depends_on:
      - login_db
    
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api-gateway:
    container_name: API-gateway
    build: ./apigateway
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8060:8060
    depends_on:
      - eureka-discovery

  # keycloak:
  #   container_name: keycloak
  #   image: quay.io/keycloak/keycloak:latest
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   command: start-dev
  #   ports:
  #     - 8090:8080
  #   volumes:
  #     - keycloak-data:/opt/jboss/keycloak/standalone/data
  
  # krakend:
  #   container_name: krakend
  #   image: devopsfaith/krakend:latest
  #   ports:
  #     - 8092:8092
  #   volumes:
  #     - ./krakend:/etc/krakend
  #   command: ["run", "-c", "/etc/krakend/krakend.json"]


volumes:
 employee_data:
 employee_login:
 keycloak-data:

#  docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:22.0.1 start-dev







