server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostName: api-gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: spring-employee-service
          uri: http://spring-employee-service:8080
          predicates:
            - Path=/employees/**
          filters:
            - AuthenticationFilter
        - id: login-service
          uri: http://login-service:8080
          predicates:
            - Path=/logins/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET}
