apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer

  template:
    metadata:
      labels:
        io.kompose.service: adminer
    spec:
      containers:
        - image: adminer:latest
          name: adminer
          ports:
            - containerPort: 8080

      restartPolicy: Always