apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: employee-db
  name: employee-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: employee-db
  template:
    metadata:
      labels:
        io.kompose.service: employee-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: employee_data
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: lerenzom/employee-database:latest
          name: employee-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: employee-data
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: employee-data
          persistentVolumeClaim:
            claimName: employee-data
