apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: login-service
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login-service
  template:
    metadata:
      labels:
        io.kompose.service: login-service
    spec:
      containers:
        - image: lerenzom/login-service:latest
          name: login-service
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-discovery:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://login-db:3307/employee_login
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
      restartPolicy: Always
