server:
    port: 8080

spring:
    application:
        name: spring-employee-service
    datasource:
        url: jdbc:mysql://employee_db:3306/employee_data
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
                    

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-discovery:8761/eureka/