apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: employee-db
  name: employee-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: employee-db
