apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: login-service
  name: login-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8080
  selector:
    io.kompose.service: login-service
