CREATE DATABASE IF NOT EXISTS employee_login;

USE employee_login;

CREATE TABLE IF NOT EXISTS employee_login_info (
    id int not null AUTO_INCREMENT,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    email varchar(60) NOT NULL,
    PRIMARY KEY (id)
);

insert into employee_login_info (id, first_name, last_name, email) values (1, 'Lerenzo', 'Martinez', 'lerenzo@lerenzo.com');
insert into employee_login_info (id, first_name, last_name, email) values (2, 'Philippine', 'Gertray', 'pgertray1@hugedomains.com');
insert into employee_login_info (id, first_name, last_name, email) values (3, 'Irvin', 'Esposita', 'iesposita2@narod.ru');
insert into employee_login_info (id, first_name, last_name, email) values (4, 'Hynda', 'Leverson', 'hleverson3@privacy.gov.au');
insert into employee_login_info (id, first_name, last_name, email) values (5, 'Tallou', 'Belone', 'tbelone4@miitbeian.gov.cn');
insert into employee_login_info (id, first_name, last_name, email) values (6, 'Thaddus', 'Gras', 'tgras5@live.com');
insert into employee_login_info (id, first_name, last_name, email) values (7, 'Elyn', 'Tremblay', 'etremblay6@storify.com');
insert into employee_login_info (id, first_name, last_name, email) values (8, 'Jo', 'Hazelgreave', 'jhazelgreave7@abc.net.au');
insert into employee_login_info (id, first_name, last_name, email) values (9, 'Stacia', 'Felgate', 'sfelgate8@jiathis.com');
insert into employee_login_info (id, first_name, last_name, email) values (10, 'Malachi', 'Legister', 'mlegister9@g.co');
insert into employee_login_info (id, first_name, last_name, email) values (11, 'Dagmar', 'Triebner', 'dtriebnera@thetimes.co.uk');
insert into employee_login_info (id, first_name, last_name, email) values (12, 'Alicea', 'Damrel', 'adamrelb@go.com');
insert into employee_login_info (id, first_name, last_name, email) values (13, 'Karel', 'Ternault', 'kternaultc@geocities.com');
insert into employee_login_info (id, first_name, last_name, email) values (14, 'Krispin', 'Barbie', 'kbarbied@photobucket.com');
insert into employee_login_info (id, first_name, last_name, email) values (15, 'Mead', 'Siegertsz', 'msiegertsze@army.mil');
insert into employee_login_info (id, first_name, last_name, email) values (16, 'Leilah', 'Hedman', 'lhedmanf@nature.com');
insert into employee_login_info (id, first_name, last_name, email) values (17, 'Melesa', 'Fisbburne', 'mfisbburneg@ovh.net');
insert into employee_login_info (id, first_name, last_name, email) values (18, 'Celesta', 'Northall', 'cnorthallh@harvard.edu');
insert into employee_login_info (id, first_name, last_name, email) values (19, 'Jourdain', 'Laden', 'jladeni@jimdo.com');
insert into employee_login_info (id, first_name, last_name, email) values (20, 'Grove', 'Le Grice', 'glegricej@nsw.gov.au');
insert into employee_login_info (id, first_name, last_name, email) values (21, 'Faydra', 'Gunton', 'fguntonk@moonfruit.com');
insert into employee_login_info (id, first_name, last_name, email) values (22, 'Washington', 'Fantham', 'wfanthaml@github.com');
insert into employee_login_info (id, first_name, last_name, email) values (23, 'Broderick', 'Tackell', 'btackellm@bbb.org');
insert into employee_login_info (id, first_name, last_name, email) values (24, 'Prentiss', 'Boddice', 'pboddicen@sakura.ne.jp');
insert into employee_login_info (id, first_name, last_name, email) values (25, 'Marty', 'Ogan', 'mogano@wp.com');
insert into employee_login_info (id, first_name, last_name, email) values (26, 'Mechelle', 'De La Haye', 'mdelahayep@nifty.com');
insert into employee_login_info (id, first_name, last_name, email) values (27, 'Berni', 'Wixon', 'bwixonq@springer.com');
insert into employee_login_info (id, first_name, last_name, email) values (28, 'Delinda', 'Jenckes', 'djenckesr@loc.gov');
insert into employee_login_info (id, first_name, last_name, email) values (29, 'Laure', 'Davidsohn', 'ldavidsohns@blinklist.com');
insert into employee_login_info (id, first_name, last_name, email) values (30, 'Florie', 'Blodg', 'fblodgt@ebay.com');
insert into employee_login_info (id, first_name, last_name, email) values (31, 'Andrea', 'Machans', 'amachansu@histats.com');
insert into employee_login_info (id, first_name, last_name, email) values (32, 'Sterling', 'Krysztowczyk', 'skrysztowczykv@omniture.com');
insert into employee_login_info (id, first_name, last_name, email) values (33, 'Gwenora', 'Bellany', 'gbellanyw@surveymonkey.com');
insert into employee_login_info (id, first_name, last_name, email) values (34, 'Alva', 'Elnaugh', 'aelnaughx@flavors.me');
insert into employee_login_info (id, first_name, last_name, email) values (35, 'Westleigh', 'Gamlyn', 'wgamlyny@wired.com');
insert into employee_login_info (id, first_name, last_name, email) values (36, 'Rebeca', 'Ballingal', 'rballingalz@over-blog.com');
insert into employee_login_info (id, first_name, last_name, email) values (37, 'Janeta', 'Knox', 'jknox10@thetimes.co.uk');
insert into employee_login_info (id, first_name, last_name, email) values (38, 'Frazier', 'Annakin', 'fannakin11@gravatar.com');
insert into employee_login_info (id, first_name, last_name, email) values (39, 'Lauralee', 'Coggan', 'lcoggan12@forbes.com');
insert into employee_login_info (id, first_name, last_name, email) values (40, 'Mariya', 'Gunderson', 'mgunderson13@stumbleupon.com');
insert into employee_login_info (id, first_name, last_name, email) values (41, 'Eustacia', 'Purkins', 'epurkins14@smugmug.com');
insert into employee_login_info (id, first_name, last_name, email) values (42, 'Sophie', 'McBoyle', 'smcboyle15@is.gd');
insert into employee_login_info (id, first_name, last_name, email) values (43, 'Stinky', 'Bloore', 'sbloore16@arstechnica.com');
insert into employee_login_info (id, first_name, last_name, email) values (44, 'Cathie', 'Mibourne', 'cmibourne17@constantcontact.com');
insert into employee_login_info (id, first_name, last_name, email) values (45, 'Benita', 'Farlow', 'bfarlow18@ebay.com');
insert into employee_login_info (id, first_name, last_name, email) values (46, 'Rosalyn', 'Lamperd', 'rlamperd19@dailymail.co.uk');
insert into employee_login_info (id, first_name, last_name, email) values (47, 'Perry', 'Rubinivitz', 'prubinivitz1a@google.ca');
insert into employee_login_info (id, first_name, last_name, email) values (48, 'Maighdiln', 'Redrup', 'mredrup1b@sina.com.cn');
insert into employee_login_info (id, first_name, last_name, email) values (49, 'Gene', 'Kitchenside', 'gkitchenside1c@whitehouse.gov');
insert into employee_login_info (id, first_name, last_name, email) values (50, 'Osbourn', 'Boss', 'oboss1d@house.gov');
insert into employee_login_info (id, first_name, last_name, email) values (51, 'Amabelle', 'Fairman', 'afairman1e@arstechnica.com');
insert into employee_login_info (id, first_name, last_name, email) values (52, 'Frankie', 'Butfield', 'fbutfield1f@goo.ne.jp');
insert into employee_login_info (id, first_name, last_name, email) values (53, 'Karine', 'Threadkell', 'kthreadkell1g@e-recht24.de');
insert into employee_login_info (id, first_name, last_name, email) values (54, 'Flossy', 'Yearne', 'fyearne1h@issuu.com');
insert into employee_login_info (id, first_name, last_name, email) values (55, 'Dorelle', 'Croney', 'dcroney1i@blinklist.com');
insert into employee_login_info (id, first_name, last_name, email) values (56, 'Deny', 'Pembridge', 'dpembridge1j@dot.gov');
insert into employee_login_info (id, first_name, last_name, email) values (57, 'Rikki', 'Arendt', 'rarendt1k@yellowbook.com');
insert into employee_login_info (id, first_name, last_name, email) values (58, 'Ambrose', 'Hodgen', 'ahodgen1l@gnu.org');
insert into employee_login_info (id, first_name, last_name, email) values (59, 'Durant', 'Klimp', 'dklimp1m@whitehouse.gov');
insert into employee_login_info (id, first_name, last_name, email) values (60, 'Lothaire', 'Bruinsma', 'lbruinsma1n@patch.com');
insert into employee_login_info (id, first_name, last_name, email) values (61, 'Humberto', 'Palmer', 'hpalmer1o@samsung.com');
insert into employee_login_info (id, first_name, last_name, email) values (62, 'Deloria', 'Woolvin', 'dwoolvin1p@indiatimes.com');
insert into employee_login_info (id, first_name, last_name, email) values (63, 'Alonzo', 'Kibbe', 'akibbe1q@unblog.fr');
insert into employee_login_info (id, first_name, last_name, email) values (64, 'Faith', 'Cockson', 'fcockson1r@geocities.com');
insert into employee_login_info (id, first_name, last_name, email) values (65, 'Freda', 'Altimas', 'faltimas1s@altervista.org');
insert into employee_login_info (id, first_name, last_name, email) values (66, 'Lynette', 'Breissan', 'lbreissan1t@oracle.com');
insert into employee_login_info (id, first_name, last_name, email) values (67, 'Sara-ann', 'Elvy', 'selvy1u@kickstarter.com');
insert into employee_login_info (id, first_name, last_name, email) values (68, 'Giavani', 'Trappe', 'gtrappe1v@cnbc.com');
insert into employee_login_info (id, first_name, last_name, email) values (69, 'Xylina', 'Olliver', 'xolliver1w@chron.com');
insert into employee_login_info (id, first_name, last_name, email) values (70, 'Brittan', 'Slatcher', 'bslatcher1x@addthis.com');
insert into employee_login_info (id, first_name, last_name, email) values (71, 'Sella', 'Broxholme', 'sbroxholme1y@fc2.com');
insert into employee_login_info (id, first_name, last_name, email) values (72, 'Fonsie', 'MacArthur', 'fmacarthur1z@admin.ch');
insert into employee_login_info (id, first_name, last_name, email) values (73, 'Chrissy', 'Randals', 'crandals20@wufoo.com');
insert into employee_login_info (id, first_name, last_name, email) values (74, 'Judy', 'Skoggings', 'jskoggings21@latimes.com');
insert into employee_login_info (id, first_name, last_name, email) values (75, 'Federico', 'Powland', 'fpowland22@noaa.gov');
insert into employee_login_info (id, first_name, last_name, email) values (76, 'Wynne', 'Trevear', 'wtrevear23@mediafire.com');
insert into employee_login_info (id, first_name, last_name, email) values (77, 'Sinclair', 'Cathrall', 'scathrall24@smugmug.com');
insert into employee_login_info (id, first_name, last_name, email) values (78, 'Estrella', 'Greenslade', 'egreenslade25@smugmug.com');
insert into employee_login_info (id, first_name, last_name, email) values (79, 'Enos', 'Revance', 'erevance26@phpbb.com');
insert into employee_login_info (id, first_name, last_name, email) values (80, 'Wallas', 'Proudley', 'wproudley27@flavors.me');
insert into employee_login_info (id, first_name, last_name, email) values (81, 'Esmaria', 'Bravey', 'ebravey28@jigsy.com');
insert into employee_login_info (id, first_name, last_name, email) values (82, 'Annabell', 'Lowden', 'alowden29@psu.edu');
insert into employee_login_info (id, first_name, last_name, email) values (83, 'Raye', 'Woolager', 'rwoolager2a@japanpost.jp');
insert into employee_login_info (id, first_name, last_name, email) values (84, 'Mandel', 'Di Baudi', 'mdibaudi2b@artisteer.com');
insert into employee_login_info (id, first_name, last_name, email) values (85, 'Manon', 'Eates', 'meates2c@php.net');
insert into employee_login_info (id, first_name, last_name, email) values (86, 'Towney', 'Costelow', 'tcostelow2d@ocn.ne.jp');
insert into employee_login_info (id, first_name, last_name, email) values (87, 'Jesse', 'Hawse', 'jhawse2e@artisteer.com');
insert into employee_login_info (id, first_name, last_name, email) values (88, 'Ophelia', 'Stocker', 'ostocker2f@ucoz.ru');
insert into employee_login_info (id, first_name, last_name, email) values (89, 'Tynan', 'Hirsthouse', 'thirsthouse2g@liveinternet.ru');
insert into employee_login_info (id, first_name, last_name, email) values (90, 'Cherilyn', 'Mintoff', 'cmintoff2h@google.com.br');
insert into employee_login_info (id, first_name, last_name, email) values (91, 'Bryna', 'Paske', 'bpaske2i@cnbc.com');
insert into employee_login_info (id, first_name, last_name, email) values (92, 'Pattie', 'Ghiron', 'pghiron2j@blinklist.com');
insert into employee_login_info (id, first_name, last_name, email) values (93, 'Marcello', 'Shoebottom', 'mshoebottom2k@bravesites.com');
insert into employee_login_info (id, first_name, last_name, email) values (94, 'Shawn', 'Mabson', 'smabson2l@scientificamerican.com');
insert into employee_login_info (id, first_name, last_name, email) values (95, 'Roselin', 'Guiso', 'rguiso2m@google.co.uk');
insert into employee_login_info (id, first_name, last_name, email) values (96, 'Trish', 'Jeffree', 'tjeffree2n@mysql.com');
insert into employee_login_info (id, first_name, last_name, email) values (97, 'Karney', 'Larkin', 'klarkin2o@simplemachines.org');
insert into employee_login_info (id, first_name, last_name, email) values (98, 'Robina', 'Van der Krui', 'rvanderkrui2p@dmoz.org');
insert into employee_login_info (id, first_name, last_name, email) values (99, 'Deidre', 'Dods', 'ddods2q@technorati.com');
insert into employee_login_info (id, first_name, last_name, email) values (100, 'Fredrick', 'Epilet', 'fepilet2r@slate.com');